# BPJS Kesehatan Reguler

In [1]:
# Data manipulation
import numpy as np
import pandas as pd
import datetime as dt

# Data visualization
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

# Ignore warning
import warnings
warnings.filterwarnings('ignore')

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [4]:
print('NumPy', np.__version__)
print('Pandas', pd.__version__)
print('Matplotlib', mpl.__version__)
print('Seaborn', sns.__version__)

NumPy 1.23.5
Pandas 1.5.3
Matplotlib 3.7.1
Seaborn 0.12.2

In [5]:
# Read the data files
df_1 = pd.read_stata('/content/drive/MyDrive/Extra Space/Healthkathon/Data Sampel Final 2022/Reguler/2015202101_kepesertaan.dta')
df_2 = pd.read_stata('/content/drive/MyDrive/Extra Space/Healthkathon/Data Sampel Final 2022/Reguler/202103_fkrtl.dta')
df_3 = pd.read_stata('/content/drive/MyDrive/Extra Space/Healthkathon/Data Sampel Final 2022/Reguler/202104_nonkapitasi.dta')
df_4 = pd.read_stata('/content/drive/MyDrive/Extra Space/Healthkathon/Data Sampel Final 2022/Reguler/202105_diagnosissekunder.dta')

## 1. Hasil Data Sampel BPJS Kesehatan

### 1.1. Kepesertaan BPJS Kesehatan

In [6]:
df_1.columns

Index(['PSTV01', 'PSTV02', 'PSTV03', 'PSTV04', 'PSTV05', 'PSTV06', 'PSTV07',
       'PSTV08', 'PSTV09', 'PSTV10', 'PSTV11', 'PSTV12', 'PSTV13', 'PSTV14',
       'PSTV15', 'PSTV16', 'PSTV17', 'PSTV18'],
      dtype='object')

In [7]:
df_1.rename(columns={
    'PSTV01': 'Nomor_Peserta',
    'PSTV02': 'Nomor_Keluarga',
    'PSTV03': 'Tanggal_Lahir_Peserta',
    'PSTV04': 'Hubungan_Keluarga',
    'PSTV05': 'Jenis_Kelamin',
    'PSTV06': 'Status_Perkawinan',
    'PSTV07': 'Kelas_Rawat',
    'PSTV08': 'Segmen_Peserta',
    'PSTV09': 'Provinsi_Tempat_Tinggal_Peserta',
    'PSTV10': 'Kabupaten_Kota_Tempat_Tinggal_Peserta',
    'PSTV11': 'Kepemilikan_Faskes',
    'PSTV12': 'Jenis_Faskes',
    'PSTV13': 'Provinsi_Faskes_Peserta',
    'PSTV14': 'Kabupaten_Kota_Faskes_Peserta',
    'PSTV15': 'Bobot',
    'PSTV16': 'Tahun_Sampel',
    'PSTV17': 'Status_Kepesertaan',
    'PSTV18': 'Tahun_Meninggal'
}, inplace=True)

In [8]:
print('\nData in 2015202101_kepesertaan.dta')
df_1.head()

Data in 2015202101_kepesertaan.dta

,Nomor_Peserta,Nomor_Keluarga,Tanggal_Lahir_Peserta,Hubungan_Keluarga,Jenis_Kelamin,Status_Perkawinan,Kelas_Rawat,Segmen_Peserta,Provinsi_Tempat_Tinggal_Peserta,Kabupaten_Kota_Tempat_Tinggal_Peserta,Kepemilikan_Faskes,Jenis_Faskes,Provinsi_Faskes_Peserta,Kabupaten_Kota_Faskes_Peserta,Bobot,Tahun_Sampel,Status_Kepesertaan,Tahun_Meninggal
0,135798314,6326929,1997-03-01,ANAK,LAKI-LAKI,TIDAK TERDEFINISI,KELAS III,PBI APBN,JAWA TENGAH,TEMANGGUNG,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,JAWA TENGAH,TEMANGGUNG,79.944771,2016,TIDAK AKTIF,NaN
1,135821984,135821984,1956-08-01,PESERTA,LAKI-LAKI,TIDAK TERDEFINISI,KELAS III,PBI APBN,JAWA TENGAH,KENDAL,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,JAWA TENGAH,KENDAL,76.267944,2016,TIDAK AKTIF,NaN
2,47640415,97101523,1993-10-01,ANAK,PEREMPUAN,CERAI,KELAS III,PBI APBN,JAWA TENGAH,KENDAL,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,JAWA TENGAH,KENDAL,227.123001,2016,AKTIF,NaN
3,95736990,43313628,1965-09-01,ISTRI,PEREMPUAN,KAWIN,KELAS III,PBI APBN,JAWA TENGAH,KENDAL,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,JAWA TENGAH,KENDAL,41.915855,2016,AKTIF,NaN
4,66860922,70450667,2010-06-24,TAMBAHAN,LAKI-LAKI,BELUM KAWIN,KELAS III,PBI APBN,JAWA TENGAH,TEMANGGUNG,SWASTA,DOKTER UMUM,JAWA TENGAH,TEMANGGUNG,21.220556,2016,AKTIF,NaN

In [9]:
df_1.shape

(2305435, 18)

In [10]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2305435 entries, 0 to 2305434
Data columns (total 18 columns):
 #   Column                                 Dtype
---  ------                                 -----
 0   Nomor_Peserta                          int32
 1   Nomor_Keluarga                         int32
 2   Tanggal_Lahir_Peserta                  datetime64[ns]
 3   Hubungan_Keluarga                      category
 4   Jenis_Kelamin                          category
 5   Status_Perkawinan                      category
 6   Kelas_Rawat                            category
 7   Segmen_Peserta                         category
 8   Provinsi_Tempat_Tinggal_Peserta        category
 9   Kabupaten_Kota_Tempat_Tinggal_Peserta  category
 10  Kepemilikan_Faskes                     category
 11  Jenis_Faskes                           category
 12  Provinsi_Faskes_Peserta                category
 13  Kabupaten_Kota_Faskes_Peserta          category
 14  Bobot                                  float32
 15  Tahun_Sampel                           int16
 16  Status_Kepesertaan                     category
 17  Tahun_Meninggal                        float64
dtypes: category(12), datetime64[ns](1), float32(1), float64(1), int16(1), int32(2)
memory usage: 114.4 MB

In [11]:
df_1.duplicated().sum()

0

In [12]:
df_1.isna().sum().sum()

2252860

In [13]:
df_1.isna().sum()

Nomor_Peserta                                  0
Nomor_Keluarga                                 0
Tanggal_Lahir_Peserta                          0
Hubungan_Keluarga                              0
Jenis_Kelamin                                  0
Status_Perkawinan                              0
Kelas_Rawat                                    0
Segmen_Peserta                                 0
Provinsi_Tempat_Tinggal_Peserta                0
Kabupaten_Kota_Tempat_Tinggal_Peserta          0
Kepemilikan_Faskes                             0
Jenis_Faskes                                   0
Provinsi_Faskes_Peserta                        0
Kabupaten_Kota_Faskes_Peserta                  0
Bobot                                          0
Tahun_Sampel                                   0
Status_Kepesertaan                             0
Tahun_Meninggal                          2252860
dtype: int64

- Jumlah missing value pada fitur `Tahun_Meninggal` sebanyak 2.252.860.

In [14]:
df_1['Tahun_Meninggal'] = df_1['Tahun_Meninggal'].fillna(0).astype(int)
df_1['Tahun_Lahir'] = df_1['Tanggal_Lahir_Peserta'].dt.year

umur = np.where(df_1['Tahun_Meninggal'] != 0,
                df_1['Tahun_Meninggal'] - df_1['Tahun_Lahir'],
                df_1['Tahun_Sampel'] - df_1['Tahun_Lahir'])
df_1['Umur'] = umur.astype(int)

In [15]:
df_1.drop(['Nomor_Keluarga', 'Hubungan_Keluarga', 'Status_Perkawinan', 'Bobot'], axis=1, inplace=True)

In [16]:
df_1.head()

,Nomor_Peserta,Tanggal_Lahir_Peserta,Jenis_Kelamin,Kelas_Rawat,Segmen_Peserta,Provinsi_Tempat_Tinggal_Peserta,Kabupaten_Kota_Tempat_Tinggal_Peserta,Kepemilikan_Faskes,Jenis_Faskes,Provinsi_Faskes_Peserta,Kabupaten_Kota_Faskes_Peserta,Tahun_Sampel,Status_Kepesertaan,Tahun_Meninggal,Tahun_Lahir,Umur
0,135798314,1997-03-01,LAKI-LAKI,KELAS III,PBI APBN,JAWA TENGAH,TEMANGGUNG,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,JAWA TENGAH,TEMANGGUNG,2016,TIDAK AKTIF,0,1997,19
1,135821984,1956-08-01,LAKI-LAKI,KELAS III,PBI APBN,JAWA TENGAH,KENDAL,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,JAWA TENGAH,KENDAL,2016,TIDAK AKTIF,0,1956,60
2,47640415,1993-10-01,PEREMPUAN,KELAS III,PBI APBN,JAWA TENGAH,KENDAL,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,JAWA TENGAH,KENDAL,2016,AKTIF,0,1993,23
3,95736990,1965-09-01,PEREMPUAN,KELAS III,PBI APBN,JAWA TENGAH,KENDAL,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,JAWA TENGAH,KENDAL,2016,AKTIF,0,1965,51
4,66860922,2010-06-24,LAKI-LAKI,KELAS III,PBI APBN,JAWA TENGAH,TEMANGGUNG,SWASTA,DOKTER UMUM,JAWA TENGAH,TEMANGGUNG,2016,AKTIF,0,2010,6

In [17]:
df_1[df_1['Provinsi_Tempat_Tinggal_Peserta'] != df_1['Provinsi_Faskes_Peserta']].count()[0]

98024

In [18]:
df_1[df_1['Kabupaten_Kota_Tempat_Tinggal_Peserta'] != df_1['Kabupaten_Kota_Faskes_Peserta']].count()[0]

277270

In [19]:
df_1.describe(include='all')

,Nomor_Peserta,Tanggal_Lahir_Peserta,Jenis_Kelamin,Kelas_Rawat,Segmen_Peserta,Provinsi_Tempat_Tinggal_Peserta,Kabupaten_Kota_Tempat_Tinggal_Peserta,Kepemilikan_Faskes,Jenis_Faskes,Provinsi_Faskes_Peserta,Kabupaten_Kota_Faskes_Peserta,Tahun_Sampel,Status_Kepesertaan,Tahun_Meninggal,Tahun_Lahir,Umur
count,2.305435e+06,2305435,2305435,2305435,2305435,2305435,2305435,2305435,2305435,2305435,2305435,2.305435e+06,2305435,2.305435e+06,2.305435e+06,2.305435e+06
unique,NaN,35581,2,4,6,35,515,10,4,35,515,NaN,5,NaN,NaN,NaN
top,NaN,2011-12-01 00:00:00,LAKI-LAKI,KELAS III,PPU,JAWA BARAT,BOGOR,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,JAWA BARAT,BOGOR,NaN,AKTIF,NaN,NaN,NaN
freq,NaN,2686,1178480,1306536,786839,298298,29903,1372616,1380395,300394,28200,NaN,1451749,NaN,NaN,NaN
first,NaN,1900-07-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
last,NaN,2021-12-30 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,1.464245e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.016751e+03,NaN,4.602592e+01,1.986104e+03,3.069076e+01
std,1.120289e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.446133e+00,NaN,3.012869e+02,2.001466e+01,1.987534e+01
min,1.500000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.016000e+03,NaN,0.000000e+00,1.900000e+03,-4.000000e+00
25%,6.029305e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.016000e+03,NaN,0.000000e+00,1.972000e+03,1.500000e+01
50%,1.216040e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.016000e+03,NaN,0.000000e+00,1.988000e+03,2.900000e+01
75%,1.964080e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.017000e+03,NaN,0.000000e+00,2.002000e+03,4.400000e+01
max,4.605590e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.021000e+03,NaN,2.021000e+03,2.021000e+03,1.170000e+02

### 1.2. Fasilitas Kesehatan Rujukan Tingkat Lanjutan (FKRTL) Diagnosis Primer

In [20]:
df_2.columns

Index(['PSTV01', 'PSTV02', 'PSTV15', 'FKP02', 'FKL02', 'FKL03', 'FKL04',
       'FKL05', 'FKL06', 'FKL07', 'FKL08', 'FKL09', 'FKL10', 'FKL11', 'FKL12',
       'FKL13', 'FKL14', 'FKL15', 'FKL15A', 'FKL16', 'FKL16A', 'FKL17',
       'FKL17A', 'FKL18', 'FKL18A', 'FKL19', 'FKL19A', 'FKL20', 'FKL21',
       'FKL22', 'FKL23', 'FKL25', 'FKL26', 'FKL27', 'FKL28', 'FKL29', 'FKL30',
       'FKL31', 'FKL32', 'FKL33', 'FKL34', 'FKL35', 'FKL36', 'FKL37', 'FKL38',
       'FKL39', 'FKL40', 'FKL41', 'FKL42', 'FKL43', 'FKL44', 'FKL45', 'FKL46',
       'FKL47', 'FKL48'],
      dtype='object')

In [21]:
df_2.rename(columns={
    'PSTV01': 'Nomor_Peserta',
    'PSTV02': 'Nomor_Keluarga',
    'PSTV15': 'Bobot',
    'FKP02' : 'ID_Kunjungan_FKTP',
    'FKL02' : 'ID_Kunjungan_FKRTL',
    'FKL03' : 'Tanggal_Datang_Kunjungan',
    'FKL04' : 'Tanggal_Pulang_Kunjungan',
    'FKL05' : 'Provinsi',
    'FKL06' : 'Kabupaten_Kota',
    'FKL07' : 'Kepemilikan',
    'FKL08' : 'Jenis',
    'FKL09' : 'Tipe',
    'FKL10' : 'Tingkat_Pelayanan',
    'FKL11' : 'Jenis_Poli',
    'FKL12' : 'Segmen_Peserta_Akses_Layanan',
    'FKL13' : 'Kelas_Rawat_Peserta',
    'FKL14' : 'Status_Pulang',
    'FKL15' : 'Kode_Nama_Diagnosis_Masuk_ICD_10',
    'FKL15A': 'Kode_Diagnosis_Masuk_ICD_10',
    'FKL16' : 'Kode_ICD_10_Diagnosis_Masuk',
    'FKL16A': 'Nama_Diagnosis_Masuk',
    'FKL17' : 'Kode_Nama_Diagnosis_Primer_ICD_10',
    'FKL17A': 'Kode_Diagnosis_Primer_ICD_10',
    'FKL18' : 'Kode_ICD_10_Diagnosis_Primer',
    'FKL18A': 'Nama_Diagnosis_Primer',
    'FKL19' : 'Kode_INACBGs',
    'FKL19A': 'Deskripsi_Kode_INACBGs',
    'FKL20' : 'INACBGs_Kode_Casemix_Main_Groups',
    'FKL21' : 'INACBGs_Tipe_Kelompok_Kasus',
    'FKL22' : 'INACBGs_Spesifikasi_Kelompok_Kasus',
    'FKL23' : 'INACBGs_Tingkat_Keparahan_Kelompok_Kasus',
    'FKL25' : 'Provinsi_Faskes_Perujuk',
    'FKL26' : 'Kabupaten_Kota_Faskes_Perujuk',
    'FKL27' : 'Kepemilikan_Faskes_Perujuk',
    'FKL28' : 'Jenis_Faskes_Perujuk',
    'FKL29' : 'Tipe_Faskes_Perujuk',
    'FKL30' : 'Jenis_Prosedur',
    'FKL31' : 'Tarif_Regional_INACBGs',
    'FKL32' : 'Group_Tarif_INACBGs',
    'FKL33' : 'Kode_Special_Sub-Acute_Groups_SA',
    'FKL34' : 'Tarif_Special_Sub-Acute_Groups_SA',
    'FKL35' : 'Kode_Special_Procedures_SP',
    'FKL36' : 'Deskripsi_Special_Procedures_SP',
    'FKL37' : 'Tarif_Special_Procedures_SP',
    'FKL38' : 'Kode_Special_Prosthesis_RR',
    'FKL39' : 'Deskripsi_Special_Prosthesis_RR',
    'FKL40' : 'Tarif_Special_Prosthesis_RR',
    'FKL41' : 'Kode_Special_Investigation_SI',
    'FKL42' : 'Deskripsi_Special_Investigation_SI',
    'FKL43' : 'Tarif_Special_Investigation_SI',
    'FKL44' : 'Kode_Special_Drugs_SD',
    'FKL45' : 'Deskripsi_Special_Drugs_SD',
    'FKL46' : 'Tarif_Special_Drugs_SD',
    'FKL47' : 'Biaya_Tagih_Faskes_Provider',
    'FKL48' : 'Biaya_Verifikasi'
}, inplace=True)

In [22]:
print('Data in 202103_fkrtl.dta:')
df_2.head()

Data in 202103_fkrtl.dta:

,Nomor_Peserta,Nomor_Keluarga,Bobot,ID_Kunjungan_FKTP,ID_Kunjungan_FKRTL,Tanggal_Datang_Kunjungan,Tanggal_Pulang_Kunjungan,Provinsi,Kabupaten_Kota,Kepemilikan,Jenis,Tipe,Tingkat_Pelayanan,Jenis_Poli,Segmen_Peserta_Akses_Layanan,Kelas_Rawat_Peserta,Status_Pulang,Kode_Nama_Diagnosis_Masuk_ICD_10,Kode_Diagnosis_Masuk_ICD_10,Kode_ICD_10_Diagnosis_Masuk,Nama_Diagnosis_Masuk,Kode_Nama_Diagnosis_Primer_ICD_10,Kode_Diagnosis_Primer_ICD_10,Kode_ICD_10_Diagnosis_Primer,Nama_Diagnosis_Primer,Kode_INACBGs,Deskripsi_Kode_INACBGs,INACBGs_Kode_Casemix_Main_Groups,INACBGs_Tipe_Kelompok_Kasus,INACBGs_Spesifikasi_Kelompok_Kasus,INACBGs_Tingkat_Keparahan_Kelompok_Kasus,Provinsi_Faskes_Perujuk,Kabupaten_Kota_Faskes_Perujuk,Kepemilikan_Faskes_Perujuk,Jenis_Faskes_Perujuk,Tipe_Faskes_Perujuk,Jenis_Prosedur,Tarif_Regional_INACBGs,Group_Tarif_INACBGs,Kode_Special_Sub-Acute_Groups_SA,Tarif_Special_Sub-Acute_Groups_SA,Kode_Special_Procedures_SP,Deskripsi_Special_Procedures_SP,Tarif_Special_Procedures_SP,Kode_Special_Prosthesis_RR,Deskripsi_Special_Prosthesis_RR,Tarif_Special_Prosthesis_RR,Kode_Special_Investigation_SI,Deskripsi_Special_Investigation_SI,Tarif_Special_Investigation_SI,Kode_Special_Drugs_SD,Deskripsi_Special_Drugs_SD,Tarif_Special_Drugs_SD,Biaya_Tagih_Faskes_Provider,Biaya_Verifikasi
0,455297864,354398080,10.273760,,134540221V000105,2021-02-26,2021-02-28,DAERAH ISTIMEWA YOGYAKARTA,KOTA YOGYAKARTA,Swasta,Rumah sakit,Khusus Ibu dan Anak,RITL,Missing,PBI APBD,Kelas 3,Sehat,P03 Fetus and newborn affected by other compli...,P03,P034,Fetus and newborn affected by caesarean delivery,,,,,P-8-17-I,"NEONATAL, BBL GROUP-5 TANPA PROSEDUR MAYOR RINGAN",P. Newborns & Neonates Groups,Rawat Inap Neonatal,17,Ringan (rawat inap keparahan 1),DAERAH ISTIMEWA YOGYAKARTA,KOTA YOGYAKARTA,Swasta,Rumah sakit,KHUSUS IBU DAN ANAK,,regional 1,3426200,,0,,,0,,,0,,,0,,,0,3426200,3426200
1,428331611,355534480,248.677673,,459250521V000580,2021-05-31,2021-06-02,JAWA TIMUR,SIDOARJO,Swasta,Rumah sakit,RS Kelas D,RITL,Missing,PBI APBD,Kelas 3,Sehat,R50 Fever of other and unknown origin,R50,R509,"Fever, unspecified",A01 Typhoid and paratyphoid fevers,A01,A010,Typhoid fever,A-4-14-I,PENYAKIT INFEKSI BAKTERI DAN PARASIT LAIN-LAI...,A. Infectious & parasitic diseases Grou,Rawat Inap Bukan Prosedur,14,Ringan (rawat inap keparahan 1),JAWA TIMUR,SIDOARJO,Swasta,Rumah sakit,RS KELAS D,,regional 1,2155300,,0,,,0,,,0,,,0,,,0,2155300,2155300
2,159537057,159537057,36.873344,,242680121V000408,2021-01-04,2021-01-07,ACEH,KOTA LHOKSEUMAWE,TNI AD,Rumah sakit,RS TNI Polri Kelas IV,RITL,Missing,PPU,Kelas 2,Sehat,A09 Other gastroenteritis and colitis of infec...,A09,A099,Gastroenteritis and colitis of unspecified origin,A01 Typhoid and paratyphoid fevers,A01,A010,Typhoid fever,A-4-14-I,PENYAKIT INFEKSI BAKTERI DAN PARASIT LAIN-LAI...,A. Infectious & parasitic diseases Grou,Rawat Inap Bukan Prosedur,14,Ringan (rawat inap keparahan 1),ACEH,KOTA LHOKSEUMAWE,TNI AD,Rumah sakit,RS TNI POLRI KELAS IV,,regional 3,2541200,,0,,,0,,,0,,,0,,,0,2541200,2541200
3,87132631,98569517,92.235886,,112271221V002764,2021-12-20,2021-12-25,JAWA TENGAH,GROBOGAN,Swasta,Rumah sakit,RS Swasta Setara Type D,RITL,Missing,PPU,Kelas 2,Sehat,A01 Typhoid and paratyphoid fevers,A01,A010,Typhoid fever,A01 Typhoid and paratyphoid fevers,A01,A010,Typhoid fever,A-4-14-I,PENYAKIT INFEKSI BAKTERI DAN PARASIT LAIN-LAI...,A. Infectious & parasitic diseases Grou,Rawat Inap Bukan Prosedur,14,Ringan (rawat inap keparahan 1),JAWA TENGAH,GROBOGAN,Swasta,Rumah sakit,RS SWASTA SETARA TYPE D,,regional 1,2586400,,0,,,0,,,0,,,0,,,0,2586400,2586400
4,25031617,14211084,78.579094,,321561121V004514,2021-11-21,2021-11-25,JAWA BARAT,BANDUNG,Swasta,Rumah sakit,RS Swasta Setara Type C,RITL,Missing,PPU,Kelas 2,Sehat,R50 Fever of other and unknown origin,R50,R509,"Fever, unspecified",A01 Typhoid and paratyphoid fevers,A01,A010,Typhoid fever,A-4-14-I,PENYAKIT INFEKSI BAKTERI DAN PARASIT LAIN-LAI...,A. Infectious & parasitic diseases Grou,Rawat Inap Bukan Prosedur,14,Ringan (rawat inap keparahan 1),JAWA BARAT,BANDUNG,Swasta,Rumah sakit,RS SWASTA SETARA TYPE C,9394 - Respiratory medication administered by ...,regional 1,2586400,,0,,,0,,,0,,,0,,,0,2586400,2586400

In [23]:
df_2.shape

(872201, 55)

In [24]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 872201 entries, 0 to 872200
Data columns (total 55 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   Nomor_Peserta                             872201 non-null  int32
 1   Nomor_Keluarga                            872201 non-null  int32
 2   Bobot                                     872201 non-null  float32
 3   ID_Kunjungan_FKTP                         872201 non-null  object
 4   ID_Kunjungan_FKRTL                        872201 non-null  object
 5   Tanggal_Datang_Kunjungan                  872201 non-null  datetime64[ns]
 6   Tanggal_Pulang_Kunjungan                  872201 non-null  datetime64[ns]
 7   Provinsi                                  872201 non-null  category
 8   Kabupaten_Kota                            872201 non-null  category
 9   Kepemilikan                               872201 non-null  category
 10  Jenis                                     872201 non-null  category
 11  Tipe                                      872201 non-null  category
 12  Tingkat_Pelayanan                         872201 non-null  category
 13  Jenis_Poli                                872201 non-null  category
 14  Segmen_Peserta_Akses_Layanan              872201 non-null  category
 15  Kelas_Rawat_Peserta                       872201 non-null  category
 16  Status_Pulang                             872201 non-null  category
 17  Kode_Nama_Diagnosis_Masuk_ICD_10          872201 non-null  category
 18  Kode_Diagnosis_Masuk_ICD_10               872201 non-null  object
 19  Kode_ICD_10_Diagnosis_Masuk               872201 non-null  object
 20  Nama_Diagnosis_Masuk                      872201 non-null  object
 21  Kode_Nama_Diagnosis_Primer_ICD_10         872201 non-null  category
 22  Kode_Diagnosis_Primer_ICD_10              872201 non-null  object
 23  Kode_ICD_10_Diagnosis_Primer              872201 non-null  object
 24  Nama_Diagnosis_Primer                     872201 non-null  object
 25  Kode_INACBGs                              872201 non-null  object
 26  Deskripsi_Kode_INACBGs                    872201 non-null  object
 27  INACBGs_Kode_Casemix_Main_Groups          872201 non-null  category
 28  INACBGs_Tipe_Kelompok_Kasus               872201 non-null  category
 29  INACBGs_Spesifikasi_Kelompok_Kasus        872201 non-null  int8
 30  INACBGs_Tingkat_Keparahan_Kelompok_Kasus  872201 non-null  category
 31  Provinsi_Faskes_Perujuk                   872201 non-null  category
 32  Kabupaten_Kota_Faskes_Perujuk             872201 non-null  category
 33  Kepemilikan_Faskes_Perujuk                872201 non-null  category
 34  Jenis_Faskes_Perujuk                      872201 non-null  category
 35  Tipe_Faskes_Perujuk                       872201 non-null  category
 36  Jenis_Prosedur                            872201 non-null  object
 37  Tarif_Regional_INACBGs                    872201 non-null  category
 38  Group_Tarif_INACBGs                       872201 non-null  int32
 39  Kode_Special_Sub-Acute_Groups_SA          872201 non-null  object
 40  Tarif_Special_Sub-Acute_Groups_SA         872201 non-null  int32
 41  Kode_Special_Procedures_SP                872201 non-null  object
 42  Deskripsi_Special_Procedures_SP           872201 non-null  object
 43  Tarif_Special_Procedures_SP               872201 non-null  int32
 44  Kode_Special_Prosthesis_RR                872201 non-null  object
 45  Deskripsi_Special_Prosthesis_RR           872201 non-null  object
 46  Tarif_Special_Prosthesis_RR               872201 non-null  int32
 47  Kode_Special_Investigation_SI             872201 non-null  object
 48  Deskripsi_Special_Investigation_SI        872201 non-null  object
 49  Tarif_Special_Investigation_SI            872201 non-null  int32
 50  Kode_Special_Drugs_SD                     872201 non-null  object
 51  Deskripsi_Special_Drugs_SD                872201 non-null  object
 52  Tarif_Special_Drugs_SD                    872201 non-null  int32
 53  Biaya_Tagih_Faskes_Provider               872201 non-null  int32
 54  Biaya_Verifikasi                          872201 non-null  int32
dtypes: category(21), datetime64[ns](2), float32(1), int32(10), int8(1), object(20)
memory usage: 211.4+ MB

In [25]:
df_2.duplicated().sum()

0

In [26]:
df_2.isna().sum().sum()

0

In [27]:
df_2['Lama_Kunjungan'] = (df_2['Tanggal_Pulang_Kunjungan'] - df_2['Tanggal_Datang_Kunjungan']).dt.days

In [28]:
df_2.drop(['Nomor_Keluarga', 'Bobot', 'Tanggal_Datang_Kunjungan', 'Tanggal_Pulang_Kunjungan',
           'Kode_Nama_Diagnosis_Masuk_ICD_10', 'Kode_Diagnosis_Masuk_ICD_10',
           'Kode_ICD_10_Diagnosis_Masuk', 'Nama_Diagnosis_Masuk',
           'Kode_Nama_Diagnosis_Primer_ICD_10', 'Kode_Diagnosis_Primer_ICD_10',
           'Kode_ICD_10_Diagnosis_Primer', 'Nama_Diagnosis_Primer', 'Kode_INACBGs',
           'Deskripsi_Kode_INACBGs', 'INACBGs_Kode_Casemix_Main_Groups',
           'INACBGs_Tipe_Kelompok_Kasus', 'INACBGs_Spesifikasi_Kelompok_Kasus',
           'INACBGs_Tingkat_Keparahan_Kelompok_Kasus'], axis=1, inplace=True)

In [29]:
df_2[df_2['Biaya_Tagih_Faskes_Provider'] != df_2['Biaya_Verifikasi']].count()

Nomor_Peserta                         527
ID_Kunjungan_FKTP                     527
ID_Kunjungan_FKRTL                    527
Provinsi                              527
Kabupaten_Kota                        527
Kepemilikan                           527
Jenis                                 527
Tipe                                  527
Tingkat_Pelayanan                     527
Jenis_Poli                            527
Segmen_Peserta_Akses_Layanan          527
Kelas_Rawat_Peserta                   527
Status_Pulang                         527
Provinsi_Faskes_Perujuk               527
Kabupaten_Kota_Faskes_Perujuk         527
Kepemilikan_Faskes_Perujuk            527
Jenis_Faskes_Perujuk                  527
Tipe_Faskes_Perujuk                   527
Jenis_Prosedur                        527
Tarif_Regional_INACBGs                527
Group_Tarif_INACBGs                   527
Kode_Special_Sub-Acute_Groups_SA      527
Tarif_Special_Sub-Acute_Groups_SA     527
Kode_Special_Procedures_SP            527
Deskripsi_Special_Procedures_SP       527
Tarif_Special_Procedures_SP           527
Kode_Special_Prosthesis_RR            527
Deskripsi_Special_Prosthesis_RR       527
Tarif_Special_Prosthesis_RR           527
Kode_Special_Investigation_SI         527
Deskripsi_Special_Investigation_SI    527
Tarif_Special_Investigation_SI        527
Kode_Special_Drugs_SD                 527
Deskripsi_Special_Drugs_SD            527
Tarif_Special_Drugs_SD                527
Biaya_Tagih_Faskes_Provider           527
Biaya_Verifikasi                      527
Lama_Kunjungan                        527
dtype: int64

In [30]:
df_2.head()

,Nomor_Peserta,ID_Kunjungan_FKTP,ID_Kunjungan_FKRTL,Provinsi,Kabupaten_Kota,Kepemilikan,Jenis,Tipe,Tingkat_Pelayanan,Jenis_Poli,Segmen_Peserta_Akses_Layanan,Kelas_Rawat_Peserta,Status_Pulang,Provinsi_Faskes_Perujuk,Kabupaten_Kota_Faskes_Perujuk,Kepemilikan_Faskes_Perujuk,Jenis_Faskes_Perujuk,Tipe_Faskes_Perujuk,Jenis_Prosedur,Tarif_Regional_INACBGs,Group_Tarif_INACBGs,Kode_Special_Sub-Acute_Groups_SA,Tarif_Special_Sub-Acute_Groups_SA,Kode_Special_Procedures_SP,Deskripsi_Special_Procedures_SP,Tarif_Special_Procedures_SP,Kode_Special_Prosthesis_RR,Deskripsi_Special_Prosthesis_RR,Tarif_Special_Prosthesis_RR,Kode_Special_Investigation_SI,Deskripsi_Special_Investigation_SI,Tarif_Special_Investigation_SI,Kode_Special_Drugs_SD,Deskripsi_Special_Drugs_SD,Tarif_Special_Drugs_SD,Biaya_Tagih_Faskes_Provider,Biaya_Verifikasi,Lama_Kunjungan
0,455297864,,134540221V000105,DAERAH ISTIMEWA YOGYAKARTA,KOTA YOGYAKARTA,Swasta,Rumah sakit,Khusus Ibu dan Anak,RITL,Missing,PBI APBD,Kelas 3,Sehat,DAERAH ISTIMEWA YOGYAKARTA,KOTA YOGYAKARTA,Swasta,Rumah sakit,KHUSUS IBU DAN ANAK,,regional 1,3426200,,0,,,0,,,0,,,0,,,0,3426200,3426200,2
1,428331611,,459250521V000580,JAWA TIMUR,SIDOARJO,Swasta,Rumah sakit,RS Kelas D,RITL,Missing,PBI APBD,Kelas 3,Sehat,JAWA TIMUR,SIDOARJO,Swasta,Rumah sakit,RS KELAS D,,regional 1,2155300,,0,,,0,,,0,,,0,,,0,2155300,2155300,2
2,159537057,,242680121V000408,ACEH,KOTA LHOKSEUMAWE,TNI AD,Rumah sakit,RS TNI Polri Kelas IV,RITL,Missing,PPU,Kelas 2,Sehat,ACEH,KOTA LHOKSEUMAWE,TNI AD,Rumah sakit,RS TNI POLRI KELAS IV,,regional 3,2541200,,0,,,0,,,0,,,0,,,0,2541200,2541200,3
3,87132631,,112271221V002764,JAWA TENGAH,GROBOGAN,Swasta,Rumah sakit,RS Swasta Setara Type D,RITL,Missing,PPU,Kelas 2,Sehat,JAWA TENGAH,GROBOGAN,Swasta,Rumah sakit,RS SWASTA SETARA TYPE D,,regional 1,2586400,,0,,,0,,,0,,,0,,,0,2586400,2586400,5
4,25031617,,321561121V004514,JAWA BARAT,BANDUNG,Swasta,Rumah sakit,RS Swasta Setara Type C,RITL,Missing,PPU,Kelas 2,Sehat,JAWA BARAT,BANDUNG,Swasta,Rumah sakit,RS SWASTA SETARA TYPE C,9394 - Respiratory medication administered by ...,regional 1,2586400,,0,,,0,,,0,,,0,,,0,2586400,2586400,4

### 1.3. Fasilitas Kesehatan Tingkat Pratama (FKTP) Non-Kapitasi

In [31]:
df_3.columns

Index(['PSTV01', 'PSTV02', 'PSTV15', 'PNK02', 'PNK03', 'PNK04', 'PNK05',
       'PNK06', 'PNK07', 'PNK08', 'PNK09', 'PNK10', 'PNK11', 'PNK12', 'PNK13',
       'PNK13A', 'PNK14', 'PNK15', 'PNK16', 'PNK17', 'PNK18'],
      dtype='object')

In [32]:
df_3.rename(columns={
    'PSTV01': 'Nomor_Peserta',
    'PSTV02': 'Nomor_Keluarga',
    'PSTV15': 'Bobot',
    'PNK02' : 'ID_Kunjungan',
    'PNK03' : 'Tanggal_Kunjungan',
    'PNK04' : 'Tanggal_Tindakan',
    'PNK05' : 'Tanggal_Pulang',
    'PNK06' : 'Provinsi_Faskes',
    'PNK07' : 'Kode_Kab_Kota_Faskes',
    'PNK08' : 'Kepemilikan_Faskes',
    'PNK09' : 'Jenis_Faskes',
    'PNK10' : 'Tipe_Faskes',
    'PNK11' : 'Tingkat_Layanan',
    'PNK12' : 'Segmen_Peserta',
    'PNK13' : 'Kode_Nama_Diagnosis_ICD_10',
    'PNK13A': 'Kode_Diagnosis_ICD_10',
    'PNK14' : 'Kode_Diagnosis_3_5_Digit',
    'PNK15' : 'Nama_Diagnosis',
    'PNK16' : 'Nama_Tindakan',
    'PNK17' : 'Biaya_Tagih',
    'PNK18' : 'Biaya_Verifikasi'
}, inplace=True)

In [33]:
print('\nData in 202104_nonkapitasi.dta:')
df_3.head()

Data in 202104_nonkapitasi.dta:

,Nomor_Peserta,Nomor_Keluarga,Bobot,ID_Kunjungan,Tanggal_Kunjungan,Tanggal_Tindakan,Tanggal_Pulang,Provinsi_Faskes,Kode_Kab_Kota_Faskes,Kepemilikan_Faskes,Jenis_Faskes,Tipe_Faskes,Tingkat_Layanan,Segmen_Peserta,Kode_Nama_Diagnosis_ICD_10,Kode_Diagnosis_ICD_10,Kode_Diagnosis_3_5_Digit,Nama_Diagnosis,Nama_Tindakan,Biaya_Tagih,Biaya_Verifikasi
0,58535615,39540462,0.949749,140270421P000283,2021-04-18,2021-04-20,2021-04-20,JAWA TIMUR,KAB. LAMONGAN,SWASTA,KLINIK PRATAMA,KLINIK RAWAT INAP,RITP,PPU,A01 Typhoid and paratyphoid fevers,A01,A01,Typhoid and paratyphoid fevers,Rawat Inap di R. Perawatan Biasa,360000,360000
1,72754862,72754862,6.303136,88220121P001458,2021-01-26,2021-01-29,2021-01-29,JAWA TIMUR,KAB. BANGKALAN,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,RAWAT INAP,RITP,PPU,A01 Typhoid and paratyphoid fevers,A01,A010,Typhoid fever,Rawat Inap di R. Perawatan Biasa,540000,540000
2,390220748,401640722,24.871052,433810421P000084,2021-04-30,2021-05-02,2021-05-02,JAWA TIMUR,KAB. TRENGGALEK,SWASTA,KLINIK PRATAMA,KLINIK RAWAT INAP,RITP,PBPU,A01 Typhoid and paratyphoid fevers,A01,A010,Typhoid fever,Rawat Inap di R. Perawatan Biasa,360000,360000
3,61351881,64119870,18.174042,199281021P000077,2021-10-02,2021-10-04,2021-10-04,LAMPUNG,KAB. TANGGAMUS,SWASTA,KLINIK PRATAMA,KLINIK RAWAT INAP,RITP,PBI APBD,A01 Typhoid and paratyphoid fevers,A01,A010,Typhoid fever,Rawat Inap di R. Perawatan Biasa,400000,400000
4,20965023,20965023,45.487633,420800621P000260,2021-06-09,2021-06-13,2021-06-13,ACEH,KAB. ACEH UTARA,SWASTA,KLINIK PRATAMA,KLINIK RAWAT INAP,RITP,BUKAN PEKERJA,A01 Typhoid and paratyphoid fevers,A01,A010,Typhoid fever,Rawat Inap di R. Perawatan Biasa,660000,660000

In [34]:
df_3.shape

(95617, 21)

In [35]:
df_3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 95617 entries, 0 to 95616
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nomor_Peserta               95617 non-null  int32
 1   Nomor_Keluarga              95617 non-null  int32
 2   Bobot                       95617 non-null  float32
 3   ID_Kunjungan                95617 non-null  object
 4   Tanggal_Kunjungan           95617 non-null  datetime64[ns]
 5   Tanggal_Tindakan            95617 non-null  datetime64[ns]
 6   Tanggal_Pulang              95617 non-null  datetime64[ns]
 7   Provinsi_Faskes             95617 non-null  category
 8   Kode_Kab_Kota_Faskes        95617 non-null  category
 9   Kepemilikan_Faskes          95617 non-null  category
 10  Jenis_Faskes                95617 non-null  category
 11  Tipe_Faskes                 95617 non-null  category
 12  Tingkat_Layanan             95617 non-null  category
 13  Segmen_Peserta              95617 non-null  category
 14  Kode_Nama_Diagnosis_ICD_10  95617 non-null  category
 15  Kode_Diagnosis_ICD_10       95617 non-null  object
 16  Kode_Diagnosis_3_5_Digit    95617 non-null  object
 17  Nama_Diagnosis              95617 non-null  object
 18  Nama_Tindakan               95617 non-null  category
 19  Biaya_Tagih                 95617 non-null  int32
 20  Biaya_Verifikasi            95617 non-null  int32
dtypes: category(9), datetime64[ns](3), float32(1), int32(4), object(4)
memory usage: 8.7+ MB

In [36]:
df_3.duplicated().sum()

0

In [37]:
df_3.isna().sum().sum()

0

In [38]:
df_3.drop(['Kode_Nama_Diagnosis_ICD_10', 'Kode_Diagnosis_ICD_10',
           'Kode_Diagnosis_3_5_Digit', 'Nama_Diagnosis'], axis=1, inplace=True)

In [39]:
df_3[df_3['Biaya_Tagih'] != df_3['Biaya_Verifikasi']].count()

Nomor_Peserta           0
Nomor_Keluarga          0
Bobot                   0
ID_Kunjungan            0
Tanggal_Kunjungan       0
Tanggal_Tindakan        0
Tanggal_Pulang          0
Provinsi_Faskes         0
Kode_Kab_Kota_Faskes    0
Kepemilikan_Faskes      0
Jenis_Faskes            0
Tipe_Faskes             0
Tingkat_Layanan         0
Segmen_Peserta          0
Nama_Tindakan           0
Biaya_Tagih             0
Biaya_Verifikasi        0
dtype: int64

In [40]:
df_3.drop(['Biaya_Verifikasi'], axis=1, inplace=True)

In [41]:
df_3.head()

,Nomor_Peserta,Nomor_Keluarga,Bobot,ID_Kunjungan,Tanggal_Kunjungan,Tanggal_Tindakan,Tanggal_Pulang,Provinsi_Faskes,Kode_Kab_Kota_Faskes,Kepemilikan_Faskes,Jenis_Faskes,Tipe_Faskes,Tingkat_Layanan,Segmen_Peserta,Nama_Tindakan,Biaya_Tagih
0,58535615,39540462,0.949749,140270421P000283,2021-04-18,2021-04-20,2021-04-20,JAWA TIMUR,KAB. LAMONGAN,SWASTA,KLINIK PRATAMA,KLINIK RAWAT INAP,RITP,PPU,Rawat Inap di R. Perawatan Biasa,360000
1,72754862,72754862,6.303136,88220121P001458,2021-01-26,2021-01-29,2021-01-29,JAWA TIMUR,KAB. BANGKALAN,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,RAWAT INAP,RITP,PPU,Rawat Inap di R. Perawatan Biasa,540000
2,390220748,401640722,24.871052,433810421P000084,2021-04-30,2021-05-02,2021-05-02,JAWA TIMUR,KAB. TRENGGALEK,SWASTA,KLINIK PRATAMA,KLINIK RAWAT INAP,RITP,PBPU,Rawat Inap di R. Perawatan Biasa,360000
3,61351881,64119870,18.174042,199281021P000077,2021-10-02,2021-10-04,2021-10-04,LAMPUNG,KAB. TANGGAMUS,SWASTA,KLINIK PRATAMA,KLINIK RAWAT INAP,RITP,PBI APBD,Rawat Inap di R. Perawatan Biasa,400000
4,20965023,20965023,45.487633,420800621P000260,2021-06-09,2021-06-13,2021-06-13,ACEH,KAB. ACEH UTARA,SWASTA,KLINIK PRATAMA,KLINIK RAWAT INAP,RITP,BUKAN PEKERJA,Rawat Inap di R. Perawatan Biasa,660000

### 1.4. FKRTL Diagnosis Sekunder

In [42]:
df_4.columns

Index(['FKL02', 'FKL24', 'FKL24A', 'FKL24B'], dtype='object')

In [43]:
df_4.rename(columns={
    'FKL02' : 'ID_Kunjungan_FKRTL',
    'FKL24' : 'Kode_Diagnosis_3_5_Digit',
    'FKL24A': 'Kode_Diagnosis_ICD_10',
    'FKL24B': 'Kode_Nama_Diagnosis_ICD_10'
}, inplace=True)

In [44]:
print('\nData in 202105_diagnosissekunder.dta:')
df_4.head()

Data in 202105_diagnosissekunder.dta:

,ID_Kunjungan_FKRTL,Kode_Diagnosis_3_5_Digit,Kode_Diagnosis_ICD_10,Kode_Nama_Diagnosis_ICD_10
0,100080221V000625,S822,S82,"S82 Fracture of lower leg, including ankle"
1,100080721V000129,P282,P28,P28 Other respiratory conditions originating i...
2,100080921V000849,N170,N17,N17 Acute renal failure
3,100081121V000654,O800,O80,O80 Single spontaneous delivery
4,100081121V000764,O700,O70,O70 Perineal laceration during delivery

In [45]:
df_4.shape

(925803, 4)

In [46]:
df_4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 925803 entries, 0 to 925802
Data columns (total 4 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   ID_Kunjungan_FKRTL          925803 non-null  object
 1   Kode_Diagnosis_3_5_Digit    925803 non-null  object
 2   Kode_Diagnosis_ICD_10       925803 non-null  object
 3   Kode_Nama_Diagnosis_ICD_10  925803 non-null  object
dtypes: object(4)
memory usage: 35.3+ MB

In [47]:
df_4.duplicated().sum()

0

In [48]:
df_4.isna().sum().sum()

0

In [49]:
df_4.drop(['Kode_Diagnosis_ICD_10', 'Kode_Nama_Diagnosis_ICD_10'], axis=1, inplace=True)

In [50]:
df_4.head()

  ID_Kunjungan_FKRTL Kode_Diagnosis_3_5_Digit
0   100080221V000625                     S822
1   100080721V000129                     P282
2   100080921V000849                     N170
3   100081121V000654                     O800
4   100081121V000764                     O700